### PR TITLE
fix: Cordova error unwrapping and passing

### LINKED ISSUE #302: Not passing native error info in Cordova
### Task specification

On iOS (I didn't verify Android), we do not pass native error info to the TS.

On this line:
https://github.com/wultra/react-native-powerauth-mobile-sdk/blob/develop/packages/react-native-powerauth-mobile-sdk/ios/PowerAuth/PAJS.h#L91

It needs to be:
```
NSData *jsonData = [NSJSONSerialization dataWithJSONObject:@{ @"code": code ? code : [NSNull null], @"message": message ? message: [NSNull null], @"errorData": [error userInfo] ? [error userInfo] : [NSNull null] } options:NSJSONWritingPrettyPrinted error:&writeError];
```

to pass the UserInfo.

On the Cordova side, this needs to be processed accordingly in the `NativeCordovaModule`

### PR DESCRIPTION
**Pull request by mbudinsky**
Fixes #302 .

This PR implements specific fixes for both `iOS` (the PAJS macros) and `Android` (throwable unwrapping in Promise.kt).
I also added small sanity check tests, we can discuss whether they're necessary:).

### CODE REVIEW

**Review by kober32 — APPROVED** [review]
Very nice 👍 

Please add an entry to the changelog :)

File: packages/cordova-powerauth-mobile-sdk/android/src/main/java/com/wultra/android/powerauth/cdv/util/Promise.kt [hunk 1]
```diff
@@ -107,8 +110,7 @@ class Promise(
    * @param userInfo WritableMap
    */
   fun reject(code: String, throwable: Throwable?, userInfo: WritableMap) {
```
Comment (marek-ch) [inline packages/cordova-powerauth-mobile-sdk/android/src/main/java/com/wultra/android/powerauth/cdv/util/Promise.kt:112]: I haven't seen so much rejections since I stopped looking for a girlfriend.

**Review by marek-ch — APPROVED** [review]
