### PR TITLE
Fix #207: Fixed problems with shared biometry key on Android

### LINKED ISSUE #207: Biometrics not working on multiple instances
This ticket covers the dependencies update due to biometry-related issue found and fixed in the native SDK. See wultra/powerauth-mobile-sdk#620 for more details.

### PR DESCRIPTION
**Pull request by hvge**
This PR fixes problem with biometry when application is using multiple `PowerAuth` instances with the configured biometry.

### CODE REVIEW

File: src/PowerAuth.ts [hunk 1]
```diff
@@ -205,7 +205,7 @@ export class PowerAuth {
      * @returns A promise with information about external pending operation.
      */
     getExternalPendingOperation(): Promise<PowerAuthExternalPendingOperation | undefined> {
-        return NativeWrapper.thisCall("getExternalPendingOperation", this.instanceId);
+        return NativeWrapper.thisCallNull("getExternalPendingOperation", this.instanceId);
```
Comment (hvge) [inline src/PowerAuth.ts:208]: Treat `null` as `undefined` to pass tests (related to #201)

**Review by kober32 — APPROVED** [review]
👍
